apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: team-catalog-backend
  namespace: teamdatajegerne
  labels:
    team: teamdatajegerne 
spec:
  image: {{image}}
  port: 8080
  azure:
    application:
      enabled: true
      replyURLs: {{emptyReplies}}
      {{#each replies as |url|}}
         - {{url}}
      {{/each}}
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: 2
    max: 2
    cpuThresholdPercentage: 50
  resources:
    limits:
      cpu: 1000m
      memory: 1024Mi
    requests:
      memory: 512Mi
  liveness:
    path: internal/isAlive
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: internal/isReady
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  vault:
    enabled: true
    paths:
      - mountPath: /var/run/secrets/nais.io/srv
        kvPath: {{vaultSrvPath}}
  prometheus:
    enabled: true
    path: internal/metrics
  webproxy: true
  envFrom:
    - secret: kafka-broker
    - secret: kafka-schreg
    - secret: env
    - secret: teamcat-db
    - secret: teamcat-redirect
    - secret: teamcat-enckey
    - secret: teamcat-users
    - secret: teamcat-admins
    - secret: graphdb
    - secret: graphdbkey
    - secret: nora-url
    - secret: processcat-url
