apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: team-catalog-backend
  namespace: teamdatajegerne
  labels:
    team: teamdatajegerne 
spec:
  image: {{image}}
  port: 80
  ingresses:
  {{#each ingresses as |url|}}
    - {{url}}
  {{/each}}
  replicas:
    min: 1
    max: 2
    cpuThresholdPercentage: 70
  resources:
    limits:
      cpu: 1000m
      memory: 768Mi
    requests:
      memory: 512Mi
  liveness:
    path: /isAlive
    timeout: 1
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  readiness:
    path: /isReady
    timeout: 1
    initialDelay: 10
    periodSeconds: 5
    failureThreshold: 30
  gcp:
    sqlInstances:
      - type: POSTGRES_11
        databases:
          - name: teamkatalog

  accessPolicy:
    inbound:
      rules:
        application: team-catalog-frontend
