name: Build and deploy

on:
  push:
    branches-ignore:
      - prod
    paths:
      - 'apps/frontend/**'

env:
  IMAGE: docker.pkg.github.com/${{ github.repository }}/teamfrontdev:${{ github.sha }}

jobs:
  build:
    name: Build and push docker
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v1
      - name: Set up node
        uses: actions/setup-node@v1
        with:
          node-version: '13.x'
      - name: npm install
        working-directory: apps/frontend
        run: npm i
      #- name: Build
      #  working-directory: apps/frontend
      #  run: npm run build
      - name: Docker
        working-directory: apps/frontend
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          docker build --tag ${IMAGE} .
          docker login docker.pkg.github.com -u ${GITHUB_REPOSITORY} -p ${GITHUB_TOKEN}
          docker push ${IMAGE}

  deploy-preprod:
    name: Deploy to NAIS GCP Preprod
    needs: build
    if: github.ref == 'refs/heads/master'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
      - uses: nais/deploy/actions/deploy@v1
        env:
          APIKEY: ${{ secrets.NAIS_DEPLOY_APIKEY }}
          CLUSTER: dev-gcp
          RESOURCE: apps/frontend/.nais/frontend.yaml
          VARS: apps/frontend/.nais/frontend-dev-vars.yaml
